//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class version : global::System.Configuration.ApplicationSettingsBase {
        
        private static version defaultInstance = ((version)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new version())));
        
        public static version Default {
            get {
                return defaultInstance;
            }
        }
    }
}
